---
title: "Preparing Data"
author: "Carys Jones"
date: '2023-01-26'
---

# Dependencies
```{r}


box::use(.. / R / dirs[dirs])
box::use(clean = ../ R / clean_data)
box::use(mods = ../ R / for_models)

box::use(readr[read_csv])
box::use(ggplot2)
box::use(dplyr)
box::use(moments)
box::use(kinship2)
box::use(sf)
box::use(tidyr)
box::use(nadiv)
box::use(magrittr[`%>%`])

```


Script to prepare data for running animal models.
First creating pedigree by merging together breeding and ringing data.
Then taking breeding attempt data and getting local environment for each individual.


PREPARE PEDIGREE


```{r}

# MERGE BREEDING AND RINGING DATA -----------------------------------------

#input clean breeding attempt data 1960-2022
breed <- read.csv(file.path(dirs$data_output, 'LT_breeding_data_greti_bluti_1960_2022.csv'), na.strings=c("", "NA"))
nrow(breed) #40255

#subset to just keep great tits 
breed_gtit <- breed %>% 
  dplyr::filter(Species == 'g')
nrow(breed_gtit) #18000

#quick summaries
nrow(breed_gtit) #18000
length(unique(breed_gtit$Pnum)) #18000
length(unique(breed_gtit$Mother)) #8532
summary(as.factor(breed_gtit$Mother)) #3831 mothers unknown  
length(unique(breed_gtit$Father)) #7216
summary(as.factor(breed_gtit$Father)) #6820


# READ IN - Ringing Data  --------------------------------------------------

ring_all <- read.csv(file.path(dirs$data_output, 'ebmp_database_ringing_record_export_GT&BT_all.csv'),
                  na.strings=c("", "NA"))

#just keep great tits and keep those only age 1
ring_gtit <- ring_all %>% 
  dplyr::filter(bto_species_code == 'GRETI',
                age == 1) 

#quick summaries
nrow(ring_gtit) #91645
length(unique(ring_gtit$Pnum)) #12711
length(unique(ring_gtit$nb)) #1121  
length(unique(ring_gtit$bto_ring)) #91645


# MERGE - ring and breed  ---------------------------------------

#merge both datasets by Pnum -   #keep all so have all parents in pedigree 
breed_ring_gtit <- merge(breed_gtit, ring_gtit, by = 'Pnum', all = T) %>%
  #keep only some columns
  dplyr::select(bto_ring, Mother, Father, sex, nest.box) %>%
  #get rid of rows that all NA
  dplyr::filter(!is.na(bto_ring) | !is.na(Mother) | !is.na(Father)) 

nrow(breed_gtit) #18000
nrow(ring_gtit) #91645

#summaries
nrow(breed_ring_gtit) #94006
length(unique(breed_ring_gtit$bto_ring)) #91646
length(unique(breed_ring_gtit$Mother)) #8532
length(unique(breed_ring_gtit$Father)) #7216

#save this 
write.csv(breed_ring_gtit, file = file.path(dirs$data_output,'GTIT-pedigree-full.csv'), row.names = F)

# CREATING PEDIGREE ----------------------------------------------------------

#rename columns 
ped_gtit_short <- breed_ring_gtit %>%
  dplyr::rename(id = bto_ring,
         dam = Mother,
         sire = Father)

head(ped_gtit_short)
nrow(ped_gtit_short) #94006

#fix the pedigree - adds any missing individuals to id column and orders it correctly
ped_gtit_short_ext_fix <- nadiv::prepPed(ped_gtit_short)

#this is the overall huge pedigree!
head(ped_gtit_short_ext_fix) 
nrow(ped_gtit_short_ext_fix) #99239. #98519

#so can save this here...
write.csv(ped_gtit_short_ext_fix, file = file.path(dirs$data_output,'GTIT-pedigree-full-fixed.csv'), row.names = F)


#I myself then keep just those that have a laying date recorded, as that's what is useful for my analysis

#make column for LD with dummy values to say if have LD recorded or not - so I can keep only informative individuals 
ped_gtit_short_ext_fix_LD <- dplyr::mutate(ped_gtit_short_ext_fix, LD_num = 
                                      ifelse(ped_gtit_short_ext_fix$id %in% breed_gtit$Father |
                                             ped_gtit_short_ext_fix$id %in% breed_gtit$Mother, 1, NA))

# subset those with a LD
ped_gtit_final <- ped_gtit_short_ext_fix_LD %>%
  dplyr::filter(!is.na(LD_num)) %>%
  droplevels() %>%
  dplyr::select(id, dam, sire)
nrow(ped_gtit_final) #15745

ped_gtit_final <- pedantics::fixPedigree(ped_gtit_final)
ped_gtit_final <- MasterBayes::orderPed(ped_gtit_final)

ped_gtit_final <-  nadiv::prepPed(ped_gtit_final)


#get pedigree stats - this take a long time to run 
# pedigree_stats <- pedantics::pedigreeStats(ped_gtit_short_ext_fix, retain = 'informative')
# nrow(pedigree_stats$analyzedPedigree) #14559
# saveRDS(pedigree_stats, file = file.path(dirs$data_output,'GTIT-pedStatSummary-full_output.rds'), row.names = F)

write.csv(ped_gtit_final, file = file.path(dirs$data_output,'GTIT-pedigree-for-asreml.csv'), row.names = F)


```


PREPARE DATA


```{r}
# GREAT TITS --------------------------------------------------------------

# BREEDING DATA ---------------------------------------------------

nrow(breed_gtit) #18000

#get rid of those with experiment codes, no LD and no Mother
breed_gtit_noNA <- breed_gtit %>%
  dplyr::filter(is.na(breed_gtit$Experiment.codes) &
                  !is.na(breed_gtit$April.lay.date))

nrow(breed_gtit_noNA) #15440
#how many have no mother
nrow(subset(breed_gtit_noNA, is.na(Mother))) #3289
nrow(subset(breed_gtit_noNA, is.na(Father))) #5791

#have both parents
nrow(subset(breed_gtit_noNA, !is.na(Mother) & !is.na(Father))) #10419
#have just mother
nrow(subset(breed_gtit_noNA, !is.na(Mother))) #13723
nrow(subset(breed_gtit_noNA, !is.na(Mother) & is.na(Father))) #3304 have no mother but have father
#have jsut father
nrow(subset(breed_gtit_noNA, !is.na(Father))) #10832
nrow(subset(breed_gtit_noNA, !is.na(Father) & is.na(Mother))) #413 have no father but have mother


breed_gtit_noNA <- breed_gtit_noNA %>%
  dplyr::filter(!is.na(Mother)) %>%
  dplyr::select('year', 'Pnum', 'Section', 'April.lay.date', 'April.hatch.date',
                                        'Clutch.size', 'Num.fledglings', 'Father', 'Mother', 'nest.box')
length(unique(breed_gtit_noNA$Mother)) #7792
length(unique(breed_gtit_noNA$Father)) #6342
length(unique(breed_gtit_noNA$Pnum)) #12151
summary(breed_gtit_noNA$April.lay.date) #-5 to 83


nrow(breed_gtit_noNA) #12151


# ADD AGE  ----------------------------------------------------------------

ring <- read.csv(file.path(dirs$data_output, 'ebmp_database_ringing_record_export_GT&BT_all.csv'), na.strings=c("", "NA"))

breed_gtit_noNA_age <- clean$get_age(breed_gtit_noNA, ring)
table(breed_gtit_noNA_age$Fem_breed_age)


# GET RID MOTHER & FATHER KNOWN 2ND BROODS & LATE BROODS ------------------

#use function - decide which ones to use 
#should say how many breeding attempts it gets rid of each time
breed_gtit_noNA_age_sub <- clean$remove_late_broods(breed_gtit_noNA_age, mothers = T, fathers = T, 
                                                    late = F, late_persection = T)
nrow(breed_gtit_noNA_age_sub) #11746 

#rename year as breeding year - make new column of yearling and adult 
breed_gtit_noNA_age_sub <- breed_gtit_noNA_age_sub %>%
  dplyr::rename('breeding_year' = 'year') %>%
  dplyr::mutate(Fbreeding_age_group = ifelse(Fem_breed_age == 1, 'Yearling', 'Adult')) 
summary(as.factor(breed_gtit_noNA_age_sub$Fbreeding_age_group)) #Adult 5428, Yearling 6444
summary(as.factor(breed_gtit_noNA_age_sub$Fem_breed_age))


```



ADD SPATIAL DATA 


```{r}


#Just open habitat data straight away 

habitat_data <- read.csv(file.path(dirs$data_output, 'Habitat_data_nestboxes.csv'), na.strings = "NA")

# nest_sub <- unique(breed_gtit_noNA_age_sub$nest.box[!(breed_gtit_noNA_age_sub$nest.box %in% habitat_data$Box)])

#now merge with breeding data!
gtit_data_sub_nb <- merge(breed_gtit_noNA_age_sub, habitat_data, by = 'Pnum')
nrow(gtit_data_sub_nb) #11786 - only a few hundred missing from before 

gtit_data_sub_nb <- gtit_data_sub_nb %>%
  dplyr::mutate(area_polygon_sqrt = sqrt(area_polygon.G))


# SPATIAL MATRIX ----------------------------------------------------------

# FINDING MIDPOINT IN SPACE FOR INDIVIDUALS -------------------------------

#data set of all that have nest box
nrow(gtit_data_sub_nb) #11786
length(unique(gtit_data_sub_nb$Mother)) #7732

summary(gtit_data_sub_nb$April.lay.date) #-5 to 78, median = 25
summary(gtit_data_sub_nb$April.hatch.date)#789 NAs
summary(gtit_data_sub_nb$Clutch.size) #49 NAs

#if individuals have multiple breeding attempts
#need to find midpoint location of nest boxes
#so can use that to make matrix of distance between all individuals

#look at how many use >1 box
gtit_data_sub_nb_multisumm <- gtit_data_sub_nb %>%
  dplyr::group_by(., Mother) %>%
  dplyr::summarise(., nest_boxes = length(unique(nest.box)),
            breed_attempts = length(nest.box))
hist(gtit_data_sub_nb_multisumm$nest_boxes)
hist(gtit_data_sub_nb_multisumm$breed_attempts)


#plot these just out of interest to see how far boxes are away from eachother?
###WORK THIS OUT
#just keep breeding attempts for mothers that moved boxes

#subset 3 birds
multi_box <- gtit_data_sub_nb %>%
  dplyr::group_by(., Mother) %>%
  dplyr::filter(length((nest.box)) > 1) %>%
  dplyr::mutate(
    x2 = dplyr::lead(x),
    y2 = dplyr::lead(y), 
    edge2 = dplyr::lead(edge.EDI.),
    alt2 = dplyr::lead(altitude.m.),
    north2 = dplyr::lead(northness),
    trees2 = dplyr::lead(No_trees_75m),
    area2 = dplyr::lead(area_polygon_sqrt),
    nest.box2 = dplyr::lead(nest.box),
    breeding_year2 = dplyr::lead(breeding_year)) %>%
  
  dplyr::mutate(dist = sqrt((x2 - x)^2 + (y2 - y)^2),
                edge_diff = abs(edge2 - edge.EDI.),
                alt_diff = abs(alt2 - altitude.m.),
                north_diff = abs(north2 - northness),
                tree_diff = abs(trees2 - No_trees_75m), 
                area_diff = abs(area2 - area_polygon_sqrt)) %>%
  
  dplyr::ungroup() %>%
  dplyr::select(Mother, breeding_year, breeding_year2, x, y , x2, y2, nest.box, nest.box2, dist,
                edge_diff, alt_diff, north_diff, tree_diff, area_diff)


#get rid of distance NA's and 0 distance
nrow(multi_box) #6683
multi_box <- multi_box %>%
  dplyr::filter(!is.na(dist))
nrow(multi_box) #4054

summary(multi_box)
length(unique(multi_box$Mother)) #2629
length(unique(multi_box$Mother)) / length(unique(gtit_data_sub_nb$Mother)) #34% mothers breed in multi years

length(unique(subset(multi_box, dist > 0)$Mother)) / length(unique(gtit_data_sub_nb$Mother)) #27.9% breed in diff boxes

#DISTANCES
median(multi_box$dist) #60.85m
mean(multi_box$dist) #93.1m
range(multi_box$dist) #0 - 2647.5m



#MEAN COORDINATES OF NEST BOX FOR MULTI NESTERS
#first make line for each breeding attempt
#then after individual will have same coords for all rows/breeding attempts
#so can then jsut keep one row per individual 

gtit_data_sub_nb <- gtit_data_sub_nb %>%
  dplyr::group_by(Mother) %>%
  dplyr::mutate(x_mean = mean(x),
                y_mean = mean(y),
                alt_mean = mean(altitude.m., na.rm = T),
                northness_mean = mean(northness, na.rm = T),
                edge_mean = mean(edge.EDI., na.rm = T),
                No_trees_75m_mean = mean(No_trees_75m, na.rm = T),
                area_polygon_sqrt_mean = mean(area_polygon_sqrt, na.rm = T)) %>%
  dplyr::ungroup()




#output data
write.csv(gtit_data_sub_nb, file = file.path(dirs$data_output,'GTIT_data_anim_mod.csv'), row.names = F)


```


