---
title: "prep matrices and compare"
author: "Carys Jones"
date: '2023-01-31'
output: html_document
---

when run models make sure make things factors beforehand

# Dependencies
```{r}


groundhog.library()


box::use(.. / R / dirs[dirs])
box::use(clean = ../ R / clean_data)
box::use(mod = ../ R / for_models)

box::use(readr[read_csv])
box::use(ggplot2[...])
box::use(dplyr[...])
box::use(moments)
box::use(kinship2)
box::use(sf)
box::use(tidyr)
box::use(pedantics)
box::use(magrittr[`%>%`])
box::use(asreml[...])
box::use(Matrix)


```



```{r Read in Data}

gtit_data_sub_nb <- read.csv(file.path(dirs$data_output, 'GTIT_data_anim_mod.csv'), na.strings=c("", "NA"))
nrow(gtit_data_sub_nb) #11661


gtit_data_sub_nb <- gtit_data_sub_nb %>% #don't make breeding year a factor?
   mutate_at(c('breeding_year', 'Mother', 'Fbreeding_age_group', 'nest.box'), as.factor) 

#to run with a subset 
#put dates as range e.g. 2011:2021, or 'ALL' to get all years of data 
breed_data <- gtit_data_sub_nb
  mod$choose_data(gtit_data_sub_nb, years = 'ALL')
unique(breed_data$breeding_year)
nrow(breed_data) #11661


#get distinct line for each mother with whole dataset
breed_data_uniq <- breed_data %>%
  distinct(., Mother, .keep_all = TRUE)
  # filter(!is.na(alt_mean) & !is.na(No_trees_75m_mean))
  
nrow(breed_data_uniq) #7680
length(unique(breed_data_uniq$Mother)) #7680

```


```{r Correlation lay and hatch}

box::use(brms[...])

# Fit model
fit <- brm(April.hatch.date ~ April.lay.date,
           data = gtit_data_sub_nb)
plot_slopes(fit, 'April.lay.date')


# Print the summary of the fitted model
summary(fit)
plot(fit)



library(marginaleffects)
plot_slopes(fit,  variables = 'April.lay.date')

mtcars %>%
  data_grid(hp = seq_range(hp, n = 101)) %>%
  # NOTE: this shows the use of ndraws to subsample within add_epred_draws()
  # ONLY do this IF you are planning to make spaghetti plots, etc.
  # NEVER subsample to a small sample to plot intervals, densities, etc.
  tidybayes::add_epred_draws(fit, ndraws = 100) %>%
  ggplot(aes(x = April.lay.date, y = April.hatch.date)) +
  geom_line(aes(y = .epred, alpha = .1)) +
  geom_point(data = gtit_data_sub_nb) +
  scale_color_brewer(palette = "Dark2")


LD_HD_mod <- lm(April.hatch.date ~ April.lay.date,
   data = gtit_data_sub_nb)
summary(LD_HD_mod)
  
effect_plot(LD_HD_mod, pred = displ, interval = TRUE, plot.points = TRUE)

ggplot(gtit_data_sub_nb, aes(x = April.lay.date, y = April.hatch.date)) + 
  geom_smooth(method = 'lm', se = T) + 
  output_plot_theme


```



# ENVIRONMENT SIM MATRIX  -------------------------------------------------

```{r Envir Matrix}

# As environmental measures may occur on different scales, we first scale and center the environmental data.
# This is done by taking away the mean (so the mean becomes 0) and dividing by the standard deviation for
# each environmental measure (so the variance becomes 1).
# First gets the relevant columns from the data

env_var <- breed_data_uniq[,c("alt_mean", "northness_mean", "edge_mean", "No_trees_75m_mean",
                        "area_polygon_sqrt")]

# Centers the data, and scales by standard deviation
env_var <- scale(env_var, center = T, scale = T)
rownames(env_var) <- breed_data_uniq$Mother

# similarity matrix between individuals
# calculates the euclidean distance between each individual's environment parameters
env_var_euc <- as.matrix(dist(env_var, method = "euclidean", diag = T, upper = T))
# then scales so that the values are between 0 and 1
env_var_euc_scal <- 1 - env_var_euc / max (env_var_euc, na.rm = TRUE)
colnames(env_var_euc_scal) <- rownames(env_var_euc_scal) <- breed_data_uniq$Mother 

p<-as(solve(env_var_euc_scal),"dgCMatrix")
p<-as.matrix(env_var_euc_scal)

#make positive definite so can run in animal model 
env_var_euc_scal_PD <- Matrix::nearPD(env_var_euc_scal)
env_matrix <- env_var_euc_scal_PD$mat

saveRDS(env_matrix, file = file.path(dirs$data_output,'env_matrix.rds'))

env_matrix <- readRDS(file.path(dirs$data_output, 'env_matrix.rds'))


```


# SPATIAL MATRIX ---------------------------------------------------------

```{r Spatial Matrix}

#make distance matrix
#make coordinates into geometries 
spatial_geom <- sf::st_as_sf(breed_data_uniq, coords = c("x_mean", "y_mean"), crs = 27700) 
#keep just geometry
geom <- spatial_geom[,c('geometry')]
rownames(geom) <- spatial_geom$Mother
#make distance matrix 
spat_mat <- as.matrix(sf::st_distance(geom, geom))
colnames(spat_mat) <- rownames(spat_mat) <- spatial_geom$Mother

#can make it to a matrix and array by doing this 
spat_mat_conv <- as.numeric(spat_mat)
dim(spat_mat_conv) <- c(nrow(spatial_geom), nrow(spatial_geom)) #give it dimensions?
colnames(spat_mat_conv) <- rownames(spat_mat_conv) <- spatial_geom$Mother

#save raw distance matrix
saveRDS(spat_mat_conv, file = file.path(dirs$data_output,'spatial_matrix_raw.rds'))

#scale the matrix - so diagonal is 1
spat_mat_conv_sc <- 1 - spat_mat_conv / max (spat_mat_conv, na.rm=TRUE)
spat_mat_conv_sc_PD <- Matrix::nearPD(spat_mat_conv_sc)
spatial_matrix <- spat_mat_conv_sc_PD$mat

subset(spatial_matrix, spatial_matrix[,1] == 608449)

saveRDS(spatial_matrix, file = file.path(dirs$data_output,'spatial_matrix.rds'))

spatial_matrix <- readRDS(file.path(dirs$data_output, 'spatial_matrix.rds'))

```


PLOTS COMPARING & MANTEL/OTHER TESTS

```{r Compare Matrices}

#Correlation of environmental variables
head(env_var)

mantel_env <- vegan::mantel(env_var$alt_mean, env_var$northness_mean, method = "spearman", permutations = 1, na.rm = TRUE)

mantel_matrices <- vegan::mantel(env_matrix, spatial_matrix, method = "spearman", permutations = 1, na.rm = TRUE)

mant()



```





# RUN MODELS ---------------------------------------------------------



```{r Prep Ped}


#pedigree data input 
ped_data <- read.csv(file.path(dirs$data_output, 'GTIT-pedigree-for-asreml.csv'), na.strings=c("", "NA"))
nrow(ped_data) #15745

#get inverse of matrix
ped_data_inv <- asreml::ainverse(ped_data)

#create another column to associate with second matrix

breed_data$Mother <- as.factor(breed_data$Mother)
breed_data$Mother2 <- breed_data$Mother
breed_data$Mother3 <- breed_data$Mother


```




```{r Run Models}

# LAYING DATE  ------------------------------------------------------------

#model basic 
LD_basic <- asreml(fixed = April.lay.date ~ 1 + Fbreeding_age_group,
                  random = ~vm(Mother, ped_data_inv) + 
                            ide(Mother, ped_data_inv) +
                            breeding_year,
                  data = breed_data)
saveRDS(LD_basic, file = file.path(dirs$model_output,'LD_basic_MIC.rds'))


#model with NB
LD_NB <- asreml::asreml(fixed = April.lay.date ~ 1 + Fbreeding_age_group,
                random = ~vm(Mother, ped_data_inv) + 
                  ide(Mother, ped_data_inv) +
                  breeding_year + 
                  nest.box,
                data = breed_data)
saveRDS(LD_NB, file = file.path(dirs$model_output,'LD_NB_MIC.rds'))


#without distance matrix
LD_spat <- asreml::asreml(fixed = April.lay.date ~ 1 + Fbreeding_age_group,
                       random = ~vm(Mother, ped_data_inv) + 
                         ide(Mother, ped_data_inv) +
                         vm(Mother2, spatial_matrix) +
                         breeding_year,
                       data = breed_data,
                  workspace = 300e6, pworkspace=300e6)
saveRDS(LD_spat, file = file.path(dirs$model_output,'LD_spat_MIC.rds'))



#model with envir sim matrix
LD_envir <- asreml::asreml(fixed = April.lay.date ~ 1 + Fbreeding_age_group,
                        random = ~vm(Mother, ped_data_inv) + 
                          ide(Mother, ped_data_inv) +
                          vm(Mother2, env_matrix) +
                          breeding_year,
                        data = breed_data,
                  workspace = 300e6, pworkspace=300e6)
saveRDS(LD_envir, file = file.path(dirs$model_output,'LD_envir_MIC.rds'))



# HATCHING DATE -----------------------------------------------------------


#model basic 
HD_basic <- asreml::asreml(fixed = April.hatch.date ~ 1 + Fbreeding_age_group,
                  random = ~vm(Mother, ped_data_inv) + 
                            ide(Mother, ped_data_inv) +
                            breeding_year,
                  data = breed_data)
saveRDS(HD_basic, file = file.path(dirs$model_output,'HD_basic_MIC.rds'))


#model with NB
HD_NB <- asreml::asreml(fixed = April.hatch.date ~ 1 + Fbreeding_age_group,
                random = ~vm(Mother, ped_data_inv) + 
                  ide(Mother, ped_data_inv) +
                  breeding_year + 
                  nest.box,
                data = breed_data)
saveRDS(HD_NB, file = file.path(dirs$model_output,'HD_NB_MIC.rds'))


#without distance matrix
HD_spat <- asreml::asreml(fixed = April.hatch.date ~ 1 + Fbreeding_age_group,
                       random = ~vm(Mother, ped_data_inv) + 
                         ide(Mother, ped_data_inv) +
                         vm(Mother2, spatial_matrix) +
                         breeding_year,
                       data = breed_data,
                  workspace = 300e6, pworkspace=300e6,
                  maxiter = 50)
saveRDS(HD_spat, file = file.path(dirs$model_output,'HD_dist_MIC.rds'))



#model with envir sim matrix
HD_envir <- asreml::asreml(fixed = April.hatch.date ~ 1 + Fbreeding_age_group,
                        random = ~vm(Mother, ped_data_inv) + 
                          ide(Mother, ped_data_inv) +
                          vm(Mother2, env_matrix) +
                          breeding_year,
                        data = breed_data,
                  workspace = 300e6, pworkspace=300e6,
                  maxiter = 50)
saveRDS(HD_envir, file = file.path(dirs$model_output,'HD_envir_MIC.rds'))





```



