---
title: "Run Model"
author: "Carys Jones"
date: '2023-02-01'
output: html_document
---


# Dependencies
```{r Dependencies}
box::use(.. / R / dirs[dirs])
box::use(clean = ../ R / clean_data)
box::use(mod = ../ R / for_models)


box::use(readr[read_csv])
box::use(ggplot2[...])
box::use(dplyr[...])
box::use(moments)
box::use(kinship2)
box::use(sf)
box::use(tidyr)
box::use(pedantics)
box::use(magrittr[`%>%`])
box::use(asreml)
box::use(tibble)
box::use(ggdist[...])
box::use(patchwork[...])


output_plot_theme <- theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.margin = unit(c(.8, .8, .8, .8), "cm"),
    plot.background = element_rect(fill = 'transparent'), 
    panel.background = element_rect(fill = 'transparent'),
    axis.text.x = element_text(size = 9, 
                               family = 'Times-Bold'),  # Adjust the size as needed
    axis.text.y = element_text(size = 8, 
                               family = 'Times-Bold'),
    axis.title.x = element_text(size = 12, 
                                family = 'Times-Bold',
                                margin = margin(t = 8)),
    axis.title.y = element_text(size = 12, 
                                family = 'Times-Bold',
                                margin = margin(r = 10)),
    legend.title = element_text(size = 8, 
                                family = 'Times-Bold',
                                hjust = 0.5 ),
    legend.text = element_text(size = 8, 
                               family = 'Times-Roman',
                               hjust = 0)
    ) 


```



OUTPUT

```{r Read in output}


# Results LD --------------------------------------------------------------

LD_basic <- readRDS(file.path(dirs$model_output, 'LD_basic_MIC.rds'))
LD_NB <- readRDS(file.path(dirs$model_output, 'LD_NB_MIC.rds'))
LD_spat <- readRDS(file.path(dirs$model_output, 'LD_spat_MIC.rds'))
LD_envir <- readRDS(file.path(dirs$model_output, 'LD_envir_MIC.rds'))

HD_basic <- readRDS(file.path(dirs$model_output, 'HD_basic_MIC.rds'))
HD_NB <- readRDS(file.path(dirs$model_output, 'HD_NB_MIC.rds'))
HD_spat <- readRDS(file.path(dirs$model_output, 'HD_dist_MIC.rds'))
HD_envir <- readRDS(file.path(dirs$model_output, 'HD_envir_MIC.rds'))


asreml::wald.asreml(LD_basic, ssType = "conditional", denDF = "numeric")

#function to make output table - var comps and herit estimates
#then also one for fixed effect output 

#basic model outputs 
summary(LD_basic)$varcomp

summary(LD_basic_resid)$varcomp
plot(LD_basic_resid)

summary(LD_NB)$varcomp
summary(LD_spat)$varcomp
summary(LD_envir)$varcomp

summary(HD_basic)$varcomp
summary(HD_NB)$varcomp
summary(HD_spat)$varcomp
summary(HD_envir)$varcomp

summary(LD_basic)$varcomp
heritability_se <- sqrt(diag(summary(LD_basic)$varcomp[,1]))


plot(HD_envir$linear.predictors)

a <- x / (x + y)


sqrt(78.98286^2 / ((2.426195 + 78.98286) ^ 2 * (7860-1)))

a_se <- sqrt((y^2 / ((x + y)^2 * (n - 1))))


nrow(breed_data)

sqrt(0.0802938*(1-0.0802938)/7680)





6.566288 / (49.082157 + 6.566288 + 6.560010 + 19.569813)
#take SE over total ?
0.8486111 / (49.082157 + 6.566288 + 6.560010 + 19.569813)

6.566288 / (6.566288 + 6.560010 + 19.569813)
0.8486111 / (6.566288 + 6.560010 + 19.569813)

heritability_se <- sqrt((19.569813^2 / (81.77827^2 * (7680 - 1))))

sqrt((y^2 / ((x + y)^2 * (n - 1))))

```



LAYING DATE OUTPUT AND PLOTS
  
```{r Lay Date Output}


#laying date results 

list_components <- c('Vby', 'Va', 'Vpe', 'Vnb', 'Vspat', 'Venv', 'Vr', 'Vp', 'Vp_yr', 'h2', 'h2_yr')

#variance componenets
LD_varcomps <- rbind(get_var_comps(model = LD_basic), 
                     get_var_comps(model = LD_NB), 
                     get_var_comps(model = LD_spat), 
                     get_var_comps(model = LD_envir))
  
LD_varcomps

#how do they change between models
#get table with rel estimate for each model for var comp
#then create columns with differences 
#for NB, and matrices are positive cause not there at all in model 1                                
LD_varcomps_changes <- LD_varcomps %>%
  dplyr::select(name, Rel_Est, model_name) %>%
  tidyr::pivot_wider(id_cols = name, names_from = model_name, values_from = Rel_Est) %>%
  dplyr::mutate(LD_basic_temp = ifelse(is.na(LD_basic), 0, LD_basic),
                LD_NB_diff = (LD_NB - LD_basic_temp) * 100,
                LD_spat_diff = (LD_spat - LD_basic_temp) * 100,
                LD_envir_diff = (LD_envir - LD_basic_temp) * 100,
                LD_basic = LD_basic * 100) %>%
  dplyr::select(name, LD_basic, LD_NB_diff, LD_spat_diff, LD_envir_diff)


#heritability
#make new little table - Vp, Vp_year, h2, h2_year
LD_herits <- rbind(get_herit(LD_varcomps, 'LD_basic'),
                   get_herit(LD_varcomps, 'LD_NB'),
                   get_herit(LD_varcomps, 'LD_spat'),
                   get_herit(LD_varcomps, 'LD_envir')) %>%
  dplyr::mutate(Rel_Est = NA,
                Rel_SE = NA,
                model_name = c(rep('LD_basic', 4),
                               rep('LD_NB', 4),
                               rep('LD_spat', 4),
                               rep('LD_envir', 4)))


head(LD_varcomps)
head(LD_herits)

#bind together and to 3 dp - combine all using dplyr

LD_all <- rbind(LD_varcomps, LD_herits) %>%
    mutate_at(vars(Est, SE, Rel_Est, Rel_SE),
              ~ if_else(is.na(.), '',
                        format(round(., 3), nsmall = 3)))
#order them by model
order <- c('LD_basic', 'LD_NB', 'LD_spat', 'LD_env')
#merge with brackets
LD_all_merge <- LD_all %>%
  dplyr::arrange(factor(model_name, levels = order)) %>%
  mutate(Est = ifelse(SE != '', paste(Est, ' (', SE,')', sep = ''), Est),
         Rel_Est = ifelse(Rel_SE != '', paste(Rel_Est, ' (', Rel_SE, ')', sep = ''), Rel_Est)) %>%
  select(-c(SE, Rel_SE))
#this is table use in results!

```

```{r Hatch Date Output}

#variance componenets
HD_varcomps <- rbind(get_var_comps(model = HD_basic), 
                     get_var_comps(model = HD_NB), 
                     get_var_comps(model = HD_spat), 
                     get_var_comps(model = HD_envir))
  
HD_varcomps

#how do they change between models
#get table with rel estimate for each model for var comp
#then create columns with differences 
#for NB, and matrices are positive cause not there at all in model 1                                
HD_varcomps_changes <- HD_varcomps %>%
  dplyr::select(name, Rel_Est, model_name) %>%
  tidyr::pivot_wider(id_cols = name, names_from = model_name, values_from = Rel_Est) %>%
  dplyr::mutate(HD_basic_temp = ifelse(is.na(HD_basic), 0, LD_basic),
                HD_NB_diff = (LD_NB - LD_basic_temp) * 100,
                HD_spat_diff = (LD_spat - LD_basic_temp) * 100,
                HD_envir_diff = (LD_envir - LD_basic_temp) * 100,
                HD_basic = LD_basic * 100) %>%
  dplyr::select(name, LD_basic, LD_NB_diff, LD_spat_diff, LD_envir_diff)


#heritability
#make new little table - Vp, Vp_year, h2, h2_year
HD_herits <- rbind(get_herit(HD_varcomps, 'HD_basic'),
                   get_herit(HD_varcomps, 'HD_NB'),
                   get_herit(HD_varcomps, 'HD_spat'),
                   get_herit(HD_varcomps, 'HD_envir')) %>%
  dplyr::mutate(Rel_Est = NA,
                Rel_SE = NA,
                model_name = c(rep('HD_basic', 4),
                               rep('HD_NB', 4),
                               rep('HD_spat', 4),
                               rep('HD_envir', 4)))


head(HD_varcomps)
head(HD_herits)

#bind together and to 3 dp - combine all using dplyr

HD_all <- rbind(HD_varcomps, HD_herits) %>%
    mutate_at(vars(Est, SE, Rel_Est, Rel_SE),
              ~ if_else(is.na(.), '',
                        format(round(., 3), nsmall = 3)))
#order them by model
order <- c('HD_basic', 'HD_NB', 'HD_spat', 'HD_env')
#merge with brackets
HD_all_merge <- HD_all %>%
  dplyr::arrange(factor(model_name, levels = order)) %>%
  mutate(Est = ifelse(SE != '', paste(Est, ' (', SE,')', sep = ''), Est),
         Rel_Est = ifelse(Rel_SE != '', paste(Rel_Est, ' (', Rel_SE, ')', sep = ''), Rel_Est)) %>%
  select(-c(SE, Rel_SE))
#this is table use in results!

```




FIGURES

```{r Lay date firgures}

#Name var comps in order 
LD_varcomps$name_plot <- factor(LD_varcomps$name, levels=c('Vr', 'Vby', 'Vnb', 'Vspat', 'Venv', 'Vpe', 'Va'))

LD_varcomps$model_name_plot <- 
  factor(LD_varcomps$model_name, levels=c('LD_basic', 'LD_NB', 'LD_spat', 'LD_envir'))


#Set labels
custom_model_labs <- gsub(' ', '\n', c("Basic", "Nestbox", "Spatial Prox.", "Breeding Env.Sim."))
custom_legend_labels <- c(expression(V[R]), 
                          expression(V[BY]), 
                          expression(V[NB]), 
                          expression(V[Spatial]), 
                          expression(V[BreedEnv]), 
                          expression(V[PE]),
                          expression(V[A]))

LD_var_comp <- 
  ggplot(LD_varcomps, 
         aes(x = model_name_plot, 
             y = Rel_Est, 
             fill = name_plot)) +
  geom_col(position = 'stack', colour = 'black') + 
  ylab('Proportion of variance') + 
  xlab('Laying Date') +
  labs(fill = "Variance \n component") + 
  scale_fill_manual(values = c("#CFCFC4", "#43BB99", "#EE8866", "#FEAABB", 
                             "#99DDFE", "#EEDD88","#77AADE"),
                    labels = custom_legend_labels) + 
  scale_x_discrete(labels = custom_model_labs) + 
  guides(fill = guide_legend(override.aes = list(color = NA))) + 
  output_plot_theme + 
  theme(axis.ticks= element_blank(),
        axis.ticks.y = element_line(colour = 'grey'),
        legend.key = element_rect(color = "transparent"),
        legend.box.margin = margin(2.5, 2.5, 2.5, 2.5), 
        legend.box.background = element_rect(color = "black", linewidth = 0.5))

LD_var_comp

ggsave(
  filename = file.path(dirs$plots, "LD_var_comp.png"),
  plot = LD_var_comp,
  scale = 1,
  width = 14,
  height = 18,
  units = "cm",
  dpi = 350,
  limitsize = FALSE,
  bg = "transparent"
)



LD_herits_sub <- LD_herits %>%
  dplyr::filter(name == 'h2_yr')

LD_herits_sub$SE <- c(0.05812232, 0.05441957, 0.02618386, 0.02379282)
#heritability - within-year
#work out how to get the SE that this gets?

LD_basic.h2 <- asreml::vpredict(LD_basic, LD_basic.h2 ~ V2 / (V2 + V3 + V4))
LD_NB.h2 <- asreml::vpredict(LD_NB, LD_NB.h2 ~ V3 / (V2 + V3 + V4 + V5))
LD_dist.h2 <- asreml::vpredict(LD_spat, LD_dist.h2 ~ V3 / (V2 + V3 + V4 + V5))
LD_envir.h2 <- asreml::vpredict(LD_envir, LD_envir.h2 ~ V3 / (V2 + V3 + V4 + V5))


LD_herits_sub$model_name_plot <- c('Basic', 'Nestbox', 'Spatial', 'Breeding env.') 
LD_herits_sub$model_name_plot  <- factor(LD_herits_sub$model_name_plot, 
                                levels = c('Breeding env.', 'Spatial', 'Nestbox', 'Basic'))

box::use(distributional[...])
LD_herit_plot <- 
  ggplot(LD_herits_sub, 
                     aes(x = model_name_plot, 
                         y = Est,
                         ydist = distributional::dist_normal(Est, SE))) +
  geom_hline(yintercept = c(0.0875, 0.1125, 0.1375, 0.1625, 0.1875, 0.2125, 0.2375), 
             linetype = "dashed", 
             color = "light grey",
             linewidth = 0.15) +
  geom_errorbar(aes(ymin = Est - SE,
                    ymax = Est + SE),
                width = 0.2,
                colour = '#2F5597') +
  geom_point(colour = '#2F5597',
             size = 5,
             shape = 23,
             fill = '#77AADE') +
  # stat_eye(colour = '#2F5597', 
  #          fill = '#77AADE',
  #          alpha = 0.7,
  #           ) + 
  scale_size_area(max_size = 1) +
  coord_flip() +
  ylab('Laying date within-year heritability') +
  output_plot_theme + 
  theme(
    panel.grid.major.x = element_line(color = "grey", 
                                      linewidth = 0.5),
    panel.grid.minor.x = element_line(color = "grey", 
                                      linewidth = 0.25, 
                                      linetype = 'dashed'),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)
  ) 
LD_herit_plot


ggsave(
  filename = file.path(dirs$plots, "LD_herit.png"),
  plot = LD_herit_plot,
  scale = 1,
  width = 30,
  height = 4,
  units = "cm",
  dpi = 350,
  limitsize = FALSE
)

```




```{r Hatch Date Figures}

#Name var comps in order 
HD_varcomps$name_plot <- factor(HD_varcomps$name, levels=c('Vr', 'Vby', 'Vnb', 'Vspat', 'Venv', 'Vpe', 'Va'))
HD_varcomps$model_name_plot <- 
  factor(HD_varcomps$model_name, levels=c('HD_basic', 'HD_NB', 'HD_spat', 'HD_envir'))

#Set labels
custom_model_labs <- gsub(' ', '\n', c("Basic", "Nestbox", "Spatial Prox.", "Breeding Env.Sim."))
custom_legend_labels <- c(expression(V[R]), 
                          expression(V[BY]), 
                          expression(V[NB]), 
                          expression(V[Spatial]), 
                          expression(V[BreedEnv]), 
                          expression(V[PE]),
                          expression(V[A]))

HD_var_comp <- 
  ggplot(HD_varcomps, 
         aes(x = model_name_plot, 
             y = Rel_Est, 
             fill = name_plot)) +
  geom_col(position = 'stack', colour = 'black') + 
  ylab('Proportion of variance') + 
  xlab('Hatching Date') +
  labs(fill = "Variance \n component") + 
  scale_fill_manual(values = c("#CFCFC4", "#43BB99", "#EE8866", "#FEAABB", 
                             "#99DDFE", "#EEDD88","#77AADE"),
                    labels = custom_legend_labels) + 
  scale_x_discrete(labels = custom_model_labs) + 
  guides(fill = guide_legend(override.aes = list(color = NA))) + 
  output_plot_theme + 
  theme(axis.ticks= element_blank(),
        axis.ticks.y = element_line(colour = 'grey'),
        legend.key = element_rect(color = "transparent"),
        legend.box.margin = margin(2.5, 2.5, 2.5, 2.5), 
        legend.box.background = element_rect(color = "black", linewidth = 0.5))

HD_var_comp

ggsave(
  filename = file.path(dirs$plots, "HD_var_comp.png"),
  plot = HD_var_comp,
  scale = 1,
  width = 14,
  height = 18,
  units = "cm",
  dpi = 350,
  limitsize = FALSE,
  bg = "transparent"
)



#heritabiltiy

HD_herits_sub <- HD_herits %>%
  dplyr::filter(name == 'h2_yr')

HD_herits_sub$SE <- c(0.05093119, 0.0473452, 0.02406109, 0.01985468)
#heritability - within-year
#work out how to get the SE that this gets?

HD_basic.h2 <- asreml::vpredict(HD_basic, HD_basic.h2 ~ V2 / (V2 + V3 + V4))
HD_NB.h2 <- asreml::vpredict(HD_NB, HD_NB.h2 ~ V3 / (V2 + V3 + V4 + V5))
HD_dist.h2 <- asreml::vpredict(HD_spat, HD_dist.h2 ~ V3 / (V2 + V3 + V4 + V5))
HD_envir.h2 <- asreml::vpredict(HD_envir, HD_envir.h2 ~ V3 / (V2 + V3 + V4 + V5))


HD_herits_sub$model_name_plot <- c('Basic', 'Nestbox', 'Spatial', 'Breeding env.') 
HD_herits_sub$model_name_plot  <- factor(HD_herits_sub$model_name_plot, 
                                levels = c('Breeding env.', 'Spatial', 'Nestbox', 'Basic'))

HD_herit_plot <- 
  ggplot(HD_herits_sub, 
                     aes(x = model_name_plot, 
                         y = Est,
                         ydist = distributional::dist_normal(Est, SE))) +
  geom_hline(yintercept = c(0.0875, 0.1125, 0.1375, 0.1625, 0.1875, 0.2125, 0.2375), 
             linetype = "dashed", 
             color = "light grey",
             linewidth = 0.15) +
  geom_errorbar(aes(ymin = Est - SE,
                    ymax = Est + SE),
                width = 0.2,
                colour = '#2F5597') +
  geom_point(colour = '#2F5597',
             size = 5,
             shape = 23,
             fill = '#77AADE') +
  # stat_eye(colour = '#2F5597', 
  #          fill = '#77AADE',
  #          alpha = 0.7,
  #           ) + 
  scale_size_area(max_size = 1) +
  coord_flip() +
  ylab('Hatching date within-year heritability') +
  output_plot_theme + 
  theme(
    panel.grid.major.x = element_line(color = "grey", 
                                      linewidth = 0.5),
    panel.grid.minor.x = element_line(color = "grey", 
                                      linewidth = 0.25, 
                                      linetype = 'dashed'),
    axis.title.y = element_blank(),
    axis.ticks = element_blank()
  ) 
HD_herit_plot


ggsave(
  filename = file.path(dirs$plots, "HD_herit.png"),
  plot = HD_herit_plot,
  scale = 1,
  width = 22,
  height = 9,
  units = "cm",
  dpi = 350,
  limitsize = FALSE
)




```



```{r Join plots}

box::use(patchwork[...])

plots <- (LD_var_comp | HD_var_comp) / LD_herit_plot / HD_herit_plot


(LD_var_comp +  HD_var_comp +  plot_layout(guides = 'collect') )/
  LD_herit_plot / HD_herit_plot



```




PLot of environment factor
```{r}

LD_varcomps_mat <- LD_varcomps %>%
  filter(name %in% c('Vnb', 'Vspat', 'Venv')) %>%
    mutate(point_colour = c("#EE8866", "#FEAABB", "#99DDFE"))
  
LD_varcomps_mat$model_name_plot <- c('Nestbox', 'Spatial', 'Breeding env.') 
LD_varcomps_mat$model_name_plot  <- factor(LD_varcomps_mat$model_name_plot, 
                                       levels = c('Breeding env.', 'Spatial', 'Nestbox'))


env_var_plot <- 
  ggplot(subset(LD_varcomps_mat, name %in% c('Vnb', 'Vspat', 'Venv')), 
       aes(x = model_name_plot, 
           y = Rel_Est)) + 
   geom_hline(yintercept = c(0.0375, 0.0625, 0.0875, 0.1125, 0.1375, 0.1625, 0.1875, 0.2125, 0.2375, 0.2625), 
             linetype = "dashed", 
             color = "light grey",
             linewidth = 0.15) +
  geom_errorbar(aes(ymin = Rel_Est - Rel_SE, 
                    ymax = Rel_Est + Rel_SE,
                    colour = point_colour), 
                width = 0.2) +
  #put different colours for each model
  geom_point(aes(colour = point_colour,
                 fill = point_colour),
             size = 5, 
             shape = 23) + 
  scale_size_area(max_size = 1) +
  theme_bw() + 
  coord_flip() +
  ylab('Proportion Variance') +
  output_plot_theme + 
  guides(fill = 'none', colour = 'none') +
  scale_y_continuous(breaks = c(0.05, 0.1, 0.15, 0.2, 0.25)) + # Set major gridline positions
  theme(
    panel.grid.major.x = element_line(color = "grey", 
                                      linewidth = 0.5),
    panel.grid.minor.x = element_line(color = "grey", 
                                      linewidth = 0.25, 
                                      linetype = 'dashed'),
    axis.title.y = element_blank(),
    axis.ticks = element_blank()
  ) 
  
env_var_plot


```




Fixed effects

```{r}


#fixed effects
summary(LD_basic, coef = T)$coef.fixed
summary(LD_NB, coef = T)$coef.fixed
summary(LD_spat, coef = T)$coef.fixed
summary(LD_envir, coef = T)$coef.fixed

#wald tests
# wald(LD_dist, denDF = "default", ssType = "conditional")$Wald
# wald.asreml(LD_dist_env, ssType = "conditional", denDF = "numeric")  # P-value for fixed effects

```



```{r}
# outputs -----------------------------------------------------------------


#AIC
LD_basic_AIC <- LD_basic$loglik
LD_NB_AIC <- LD_NB$loglik
LD_spat_AIC <- LD_spat$loglik
LD_envir_AIC <- LD_envir$loglik


#heritability - within-year
LD_basic.h2 <- asreml::vpredict(LD_basic, LD_basic.h2 ~ V2 / (V2 + V3 + V4))
LD_NB.h2 <- asreml::vpredict(LD_NB, LD_NB.h2 ~ V3 / (V2 + V3 + V4 + V5))
LD_dist.h2 <- asreml::vpredict(LD_spat, LD_dist.h2 ~ V3 / (V2 + V3 + V4 + V5))
LD_envir.h2 <- asreml::vpredict(LD_envir, LD_envir.h2 ~ V3 / (V2 + V3 + V4 + V5))

#heritability - total
LD_basic.h2tot <- asreml::vpredict(LD_basic, LD_basic.h2tot ~ V2 / (V1 + V2 + V3 + V4))
LD_basic.resid.h2tot <- asreml::vpredict(LD_basic_resid, LD_basic.h2tot ~ V2 / (V1 + V2 + V3 + V4))


HD_NB.h2tot <- asreml::vpredict(HD_NB, LD_NB.h2tot ~ V3 / (V1 + V2 + V3 + V4 + V5))
HD_dist.h2tot <- asreml::vpredict(HD_spat, LD_dist.h2tot ~ V3 / (V1 + V2 + V3 + V4 + V5))
LD_envir.h2tot <- asreml::vpredict(LD_envir, LD_envir.h2tot ~ V3 / (V1 + V2 + V3 + V4 + V5))


#prop explained by NB, and matrices within year
LD_NB.SPACEprop <- asreml::vpredict(LD_NB, LD_NB.SPACEprop ~ V2 / (V1 +V2 + V3 + V4 + V5))
LD_dist.SPACEprop <- asreml::vpredict(LD_spat, LD_dist.SPACEprop ~ V2 / (V2 + V3 + V4 + V5))
LD_envir.SPACEprop <- asreml::vpredict(LD_envir, LD_envir.SPACEprop ~ V2 / (V2 + V3 + V4 + V5))


```


Test significance of models 

```{r Compare Models}

#LAY DATE 

#Basic vs nest box
2*(LD_NB$loglik - LD_basic$loglik)
1-pchisq(2*(LD_NB$loglik - LD_basic$loglik),1)

#nest box vs spatial
2*(LD_spat$loglik - LD_NB$loglik)
1-pchisq(2*(LD_spat$loglik - LD_NB$loglik),1)

#nest box vs environ
2*(LD_envir$loglik - LD_NB$loglik)
1-pchisq(2*(LD_envir$loglik - LD_NB$loglik),1)

#spatial vs environ
2*(LD_spat$loglik - LD_envir$loglik)
1-pchisq(2*(LD_spat$loglik - LD_envir$loglik),1)



#HATCH DATE 

#Basic vs nest box
2*(HD_NB$loglik - HD_basic$loglik)
1-pchisq(2*(HD_NB$loglik - HD_basic$loglik),1)

#nest box vs spatial
2*(HD_spat$loglik - HD_NB$loglik)
1-pchisq(2*(HD_spat$loglik - HD_NB$loglik),1)

#nest box vs environ
2*(HD_envir$loglik - HD_NB$loglik)
1-pchisq(2*(HD_envir$loglik - HD_NB$loglik),1)

#spatial vs environ
2*(HD_spat$loglik - HD_envir$loglik)
1-pchisq(2*(HD_spat$loglik - HD_envir$loglik),1)



```


```{r}
# var comp  ---------------------------------------------------------------


####FOR POSTER

##ACCOUNTING FOR SPACE
#with and without BY
LD_space <- rbind(LD_NB.SPACEprop,
                  LD_dist.SPACEprop,
                  LD_envir.SPACEprop
)

LD_space <- tibble::rownames_to_column(LD_space, var = "model")
LD_space$model_simp <- c( '2', '3', '4')

variance_space <- ggplot(transform(LD_space, model_simp = factor(model_simp, levels=c('4','3','2'))),
       aes(x = Estimate, y = model_simp)) +
  geom_col(fill = "#79B0CD") + 
  geom_errorbar(aes(xmin = Estimate - SE, xmax = Estimate + SE), colour = "#608DA6", width = 0.2) +
  ylab('') + xlab('Proportion within-year variance (SE)') +
  theme(panel.background = element_rect(fill='transparent'), #transparent panel bg
        plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
        panel.grid.major = element_blank(), #remove major gridlines
        panel.grid.minor = element_blank(), #remove minor gridlines
        legend.background = element_rect(fill='transparent'), #transparent legend bg
        legend.box.background = element_rect(fill='transparent'), #transparent legend panel
        # panel.background = element_rect(fill = "#B4C7E7", color = "#B4C7E7"),
        # plot.background = element_rect(fill = "#B4C7E7", color = "#B4C7E7"),
        # panel.grid.major.x = element_blank(),
        # panel.grid.minor.x = element_blank(),
        # panel.grid.minor.y = element_blank(),
        # panel.grid.major.y = element_blank(),
        #axis.title.x = element_text(colour = "#a4948c"),
        #axis.title.y = element_text(colour = "#a4948c"),
        text = element_text(color="#2F5597", face = 'bold', size = 14), 
        axis.text = element_text(color="#2F5597", face = 'bold', size = 10))

variance_space

ggsave(
  filename = "./plots/variance_space_transp_2.png",
  plot = variance_space,
  scale = 1,
  width = 22,
  height = 9,
  units = "cm",
  dpi = 350,
  limitsize = FALSE,
  bg = "transparent"
)












```


HATCHING DATE !!!

```{r}

# Results HD  -------------------------------------------------------------

HD_basic <- readRDS('./output/AnMod_test_basic_HD_FINAL.rds')
HD_NB <- readRDS('./output/AnMod_test_NB_HD_FINAL.rds')
HD_envir <- readRDS('./output/AnMod_test_envir_HD_FINAL.rds')
HD_dist <- readRDS('./output/AnMod_test_dist_HD_FINAL.rds')

summary(HD_basic)$varcomp
summary(HD_NB)$varcomp
summary(HD_dist)$varcomp
summary(HD_envir)$varcomp

#make to little tables of raw var comps
HD_basic_varcomp <- summary(HD_basic)$varcomp
HD_basic_varcomp <- rownames_to_column(HD_basic_varcomp, var = "comp")
HD_basic_varcomp$model <- 'model 1'

HD_NB_varcomp <- summary(HD_NB)$varcomp
HD_NB_varcomp <- rownames_to_column(HD_NB_varcomp, var = "comp")
HD_NB_varcomp$model <- 'model 2'

HD_dist_varcomp <- summary(HD_dist)$varcomp
HD_dist_varcomp <- rownames_to_column(HD_dist_varcomp, var = "comp")
HD_dist_varcomp$model <- 'model 3'

HD_envir_varcomp <- summary(HD_envir)$varcomp
HD_envir_varcomp <- rownames_to_column(HD_envir_varcomp, var = "comp")
HD_envir_varcomp$model <- 'model 4'

#combine
HD_varcomp_comb <- rbind(HD_basic_varcomp, HD_NB_varcomp, HD_dist_varcomp, HD_envir_varcomp)

#fixed effects
summary(HD_basic, coef = T)$coef.fixed
summary(HD_NB, coef = T)$coef.fixed
summary(HD_dist, coef = T)$coef.fixed
summary(HD_envir, coef = T)$coef.fixed

#AIC
HD_basic_AIC <- HD_basic$loglik
HD_NB_AIC <- HD_NB$loglik
HD_dist_AIC <- HD_dist$loglik
HD_envir_AIC <- HD_envir$loglik

#total phenotypic variance
HD_basic.VP <- vpredict(HD_basic, HD_basic.VP ~ V1 + V2 + V3 + V4)
HD_NB.VP <- vpredict(HD_NB, HD_NB.VP ~ V1 + V2 + V3 + V4 + V5)
HD_dist.VP <- vpredict(HD_dist, HD_dist.VP ~ V1 + V2 + V3 + V4 + V5)
HD_envir.VP <- vpredict(HD_envir, HD_envir.VP ~ V1 + V2 + V3 + V4 + V5)

#total phenotypic variance within year
HD_basic.VPtot <- vpredict(HD_basic, HD_basic.VPtot ~  V2 + V3 + V4)
HD_NB.VPtot <- vpredict(HD_NB, HD_NB.VPtot ~ V2 + V3 + V4 + V5)
HD_dist.VPtot <- vpredict(HD_dist_test, HD_dist_test.VPtot ~ V2 + V3 + V4 + V5)
HD_envir.VPtot <- vpredict(HD_envir, HD_envir.VPtot ~ V2 + V3 + V4 + V5)

#heritability - total
HD_basic.h2tot <- vpredict(HD_basic, HD_basic.h2tot ~ V2 / (V2 + V3 + V4))
HD_NB.h2tot <- vpredict(HD_NB, HD_NB.h2tot ~ V3 / (V2 + V3 + V4 + V5))
HD_dist.h2tot <- vpredict(HD_dist_test, HD_dist_test.h2tot ~ V3 / (V2 + V3 + V4 + V5))
HD_envir.h2tot <- vpredict(HD_envir, HD_envir_test.h2tot ~ V3 / (V2 + V3 + V4 + V5))

#heritability - within-year
HD_basic.h2 <- vpredict(HD_basic, HD_basic.h2 ~ V2 / (V1 + V2 + V3 + V4))
HD_NB.h2 <- vpredict(HD_NB, HD_NB.h2 ~ V3 / (V1 + V2 + V3 + V4 + V5))
HD_dist.h2 <- vpredict(HD_dist, HD_dist.h2 ~ V3 / (V1 + V2 + V3 + V4 + V5))
HD_envir.h2 <- vpredict(HD_envir, HD_envir.h2 ~ V3 / (V1 + V2 + V3 + V4 + V5))


#get prop explained by each var comp
#breed year
HD_basic.BY <- vpredict(HD_basic, BY ~ V1)
HD_NB.BY <- vpredict(HD_NB, BY ~ V1)
HD_dist.BY <- vpredict(HD_dist, BY ~ V1)
HD_envir.BY <- vpredict(HD_envir, BY ~ V1)
#mother vm
HD_basic.VM <- vpredict(HD_basic, VM ~ V2 )
HD_NB.VM <- vpredict(HD_NB, VM ~ V3 )
HD_dist.VM <- vpredict(HD_dist, VM ~ V3 )
HD_envir.VM <- vpredict(HD_envir, VM ~ V3 )
#mother ide
HD_basic.IDE <- vpredict(HD_basic, IDE ~ V3)
HD_NB.IDE <- vpredict(HD_NB, IDE ~ V4)
HD_dist.IDE <- vpredict(HD_dist, IDE ~ V4)
HD_envir.IDE <- vpredict(HD_envir, IDE ~ V4)
#residuls
HD_basic.R <- vpredict(HD_basic, R ~ V4)
HD_NB.R <- vpredict(HD_NB, R ~ V5)
HD_dist.R <- vpredict(HD_dist, R ~ V5)
HD_envir.R <- vpredict(HD_envir, R ~ V5)
#matrix
HD_basic.NONE <- 0
HD_NB.NB <- vpredict(HD_NB, NB ~ V2)
HD_dist.DIST <- vpredict(HD_dist, DIST ~ V2)
HD_envir.ENVIR <- vpredict(HD_envir, ENVIR ~ V2)


#test model signif
#
2*(HD_dist$loglik-HD_NB$loglik)
1-pchisq(2*(HD_dist$loglik-HD_NB$loglik),1)

#
2*(HD_dist$loglik-HD_envir$loglik)
1-pchisq(2*(HD_dist$loglik-HD_envir$loglik),1)

#
2*(HD_envir$loglik-HD_NB$loglik)
1-pchisq(2*(HD_envir$loglik-HD_NB$loglik),1)





#combine
HD_basic_comb <- rbind(HD_basic.BY, 
                    HD_basic.VM,
                    HD_basic.IDE, 
                    HD_basic.R
)

HD_basic_comb <- rownames_to_column(HD_basic_comb, var = "variable")
HD_basic_comb$model <- 'model 1'
HD_basic_comb$prop <- HD_basic_comb$Estimate / sum(HD_basic_comb$Estimate)
HD_basic_comb$propSE <- HD_basic_comb$SE / sum(HD_basic_comb$SE)



HD_NB_comb <- rbind(HD_NB.BY, 
                 HD_NB.VM,
                 HD_NB.IDE, 
                 HD_NB.R,
                 HD_NB.NB
)

HD_NB_comb <- rownames_to_column(HD_NB_comb, var = "variable")
HD_NB_comb$model <- 'model 2'
HD_NB_comb$prop <- HD_NB_comb$Estimate / sum(HD_NB_comb$Estimate)
HD_NB_comb$propSE <- HD_NB_comb$SE / sum(HD_NB_comb$SE)



HD_dist_comb <- rbind(HD_dist.BY, 
                   HD_dist.VM,
                   HD_dist.IDE, 
                   HD_dist.R,
                   HD_dist.DIST
)

HD_dist_comb <- rownames_to_column(HD_dist_comb, var = "variable")
HD_dist_comb$model <- 'model 3'
HD_dist_comb$prop <- HD_dist_comb$Estimate / sum(HD_dist_comb$Estimate)
HD_dist_comb$propSE <- HD_dist_comb$SE / sum(HD_dist_comb$SE)


HD_envir_comb <- rbind(HD_envir.BY, 
                    HD_envir.VM,
                    HD_envir.IDE, 
                    HD_envir.R,
                    HD_envir.ENVIR
)

HD_envir_comb <- rownames_to_column(HD_envir_comb, var = "variable")
HD_envir_comb$model <- 'model 4'
HD_envir_comb$prop <- HD_envir_comb$Estimate / sum(HD_envir_comb$Estimate)
HD_envir_comb$propSE <- HD_envir_comb$SE / sum(HD_envir_comb$SE)


HD_all_comb <- rbind(HD_basic_comb, HD_NB_comb, HD_dist_comb, HD_envir_comb)

#plot variance componenets
# all_comb$model = factor(all_comb$model, levels = c('HD_basic', 'HD_NB', 'HD_dist', 'HD_envir'))
HD_var_comp <- ggplot(HD_all_comb, aes(x = model, y = prop, fill = variable)) +
  geom_col(position = 'stack') + 
  ylab('Proportion of variance') + xlab(label = '') +
  scale_fill_manual(values=c("#43BB99", "#99DDFE", "#FEAABB",
                             "#EEDD88", "#EE8866", "#77AADE", 'dark grey')) +
  theme(
    axis.title.y = element_blank(),
    panel.border=element_blank(),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    plot.margin = unit(c(.8, .8, .8, .8), "cm"),
    plot.background =
      ggplot2::element_rect(fill = 'transparent'),
    panel.background =
      ggplot2::element_rect(fill = 'transparent')
  )

ggsave(
  filename = "var_comp_HD.png",
  plot = HD_var_comp,
  scale = 1,
  width = 14,
  height = 18,
  units = "cm",
  dpi = 350,
  limitsize = FALSE,
  bg = "transparent"
)

#plot heritability

HD_herit <- rbind(HD_basic.h2, HD_NB.h2, HD_dist.h2, HD_envir.h2)
HD_herit <- rownames_to_column(HD_herit, var = "model")
HD_herit$model2 <- c('model 1', 'model 2', 'model 3', 'model 4')

HD_herit$model2 = factor(HD_herit$model2, levels = c('model 4', 'model 3', 
                                               'model 2', 'model 1'))
HD_herit_plot <- ggplot(HD_herit, aes(x = model2, y = Estimate)) +
  geom_col(fill = '#77AADE') + 
  geom_errorbar(aes(ymin = Estimate - SE, ymax = Estimate + SE)) +
  theme_bw() + coord_flip() +
  ylab('Within-year heritability') +
  theme(
    axis.title.y = element_blank(),
    panel.border=element_blank(),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    plot.margin = unit(c(.8, .8, .8, .8), "cm"),
    plot.background =
      ggplot2::element_rect(fill = 'transparent'),
    panel.background =
      ggplot2::element_rect(fill = 'transparent')
  )

ggsave(
  filename = "herit_plot_HD.png",
  plot = HD_herit_plot,
  scale = 1,
  width = 20,
  height = 5,
  units = "cm",
  dpi = 350,
  limitsize = FALSE,
  bg = "transparent"
)




###combine to make table

#empty rows for Nb envir and spatial
HD_env_row <- data.frame('variable' = 'ENV', 'component' = '-', 'std.error' = '-',
                      'prop' = '-', 'propSE' = '-')
HD_dist_row <- data.frame('variable' = 'DIST', 'component' = '-', 'std.error' = '-',
                       'prop' = '-', 'propSE' = '-')
HD_NB_row <- data.frame('variable' = 'NB', 'component' = '-', 'std.error' = '-',
                     'prop' = '-', 'propSE' = '-')

#these have raw values
#HD_basic_varcomp, HD_NB_varcomp, HD_dist_varcomp, HD_envir_varcomp

HD_basic_est <- rbind(cbind(HD_basic_comb[1], HD_basic_varcomp[2], HD_basic_varcomp[3],
                            HD_basic_comb[5], HD_basic_comb[6]), HD_NB_row, HD_dist_row, HD_env_row)

HD_NB_est <- rbind(cbind(HD_NB_comb[1], HD_NB_varcomp[2], HD_NB_varcomp[3],
                         HD_NB_comb[5], HD_NB_comb[6]), HD_dist_row, HD_env_row)

HD_dist_est <- rbind(cbind(HD_dist_comb[1], HD_dist_varcomp[2], HD_dist_varcomp[3],
                           HD_dist_comb[5], HD_dist_comb[6]), HD_NB_row)
#make sure rows in same order as others
HD_dist_est <- HD_dist_est %>% slice(-5) %>% bind_rows(HD_dist_est %>% slice(5))
HD_dist_est <- rbind(HD_dist_est, HD_env_row)

HD_env_est <- rbind(cbind(HD_envir_comb[1], HD_envir_varcomp[2], HD_envir_varcomp[3],
                          HD_envir_comb[5], HD_envir_comb[6]), HD_NB_row, HD_dist_row)
HD_env_est <- HD_env_est %>% slice(-5) %>% bind_rows(HD_env_est %>% slice(5))


#these have proportions
#basic_comb, NB_comb, dist_comb, envir_comb

HD_basic_est2 <- rbind(HD_basic.VPtot, HD_basic.VP, HD_basic.h2tot, HD_basic.h2)
HD_NB_est2 <- rbind(HD_NB.VP, HD_NB.VPtot, HD_NB.h2tot, HD_NB.h2)
HD_dist_est2 <- rbind(HD_dist.VP, HD_dist.VPtot, HD_dist.h2tot, HD_dist.h2)
HD_env_est2 <- rbind(HD_envir.VP, HD_envir.VPtot, HD_envir.h2tot, HD_envir.h2)


#output these 
HD_all_est <- cbind(HD_basic_est, HD_NB_est, HD_dist_est, HD_env_est)
write.csv(HD_all_est, file = './output/AnMod_estimates_varcomps_HD.csv')


HD_all_est2 <- cbind(HD_basic_est2, HD_NB_est2, HD_dist_est2, HD_env_est2)
write.csv(HD_all_est2, file = './output/AnMod_estimates_tots_HD.csv')





```